repos:
  - repo: https://github.com/kynan/nbstripout
    rev: '0.7.1'  # Use the latest commit on the master branch
    hooks:
      - id: nbstripout

  - repo: https://github.com/psf/black
    rev: '24.8.0'  # Specify the version of Black you want to use
    hooks:
      - id: black
        args: ['--line-length', '118']  # Set line length to 118

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0  # Use the appropriate version for the hooks
    hooks:
      - id: trailing-whitespace
      - id: check-yaml
      - id: end-of-file-fixer
      - id: check-added-large-files
