#interactive
bsub  -R "tensorcore" -gpu num=1:j_exclusive=yes:mode=shared:gmem=10G -q gpu-debian -o /dkfz/cluster/gpu/data/OE0441/c306h/logs/%J.log -e /dkfz/cluster/gpu/data/OE0441/c306h/logs/%J.err ". ~/radioactive.sh  && python /home/c306h/radioactive/universal-models/src/radioa/experiments_runner.py --config ./configs/interactive_prompt_ScribblePrompter_D1_1.yaml";
bsub  -R "tensorcore" -gpu num=1:j_exclusive=yes:mode=shared:gmem=10G -q gpu-debian -o /dkfz/cluster/gpu/data/OE0441/c306h/logs/%J.log -e /dkfz/cluster/gpu/data/OE0441/c306h/logs/%J.err ". ~/radioactive.sh  && python /home/c306h/radioactive/universal-models/src/radioa/experiments_runner.py --config ./configs/interactive_prompt_ScribblePrompter_D1_2.yaml";
bsub  -R "tensorcore" -gpu num=1:j_exclusive=yes:mode=shared:gmem=10G -q gpu-debian -o /dkfz/cluster/gpu/data/OE0441/c306h/logs/%J.log -e /dkfz/cluster/gpu/data/OE0441/c306h/logs/%J.err ". ~/radioactive.sh  && python /home/c306h/radioactive/universal-models/src/radioa/experiments_runner.py --config ./configs/interactive_prompt_ScribblePrompter_D2_1.yaml";
bsub  -R "tensorcore" -gpu num=1:j_exclusive=yes:mode=shared:gmem=10G -q gpu-debian -o /dkfz/cluster/gpu/data/OE0441/c306h/logs/%J.log -e /dkfz/cluster/gpu/data/OE0441/c306h/logs/%J.err ". ~/radioactive.sh  && python /home/c306h/radioactive/universal-models/src/radioa/experiments_runner.py --config ./configs/interactive_prompt_ScribblePrompter_D2_2.yaml";
bsub  -R "tensorcore" -gpu num=1:j_exclusive=yes:mode=shared:gmem=10G -q gpu-debian -o /dkfz/cluster/gpu/data/OE0441/c306h/logs/%J.log -e /dkfz/cluster/gpu/data/OE0441/c306h/logs/%J.err ". ~/radioactive.sh  && python /home/c306h/radioactive/universal-models/src/radioa/experiments_runner.py --config ./configs/interactive_prompt_ScribblePrompter_D3_1.yaml";
bsub  -R "tensorcore" -gpu num=1:j_exclusive=yes:mode=shared:gmem=10G -q gpu-debian -o /dkfz/cluster/gpu/data/OE0441/c306h/logs/%J.log -e /dkfz/cluster/gpu/data/OE0441/c306h/logs/%J.err ". ~/radioactive.sh  && python /home/c306h/radioactive/universal-models/src/radioa/experiments_runner.py --config ./configs/interactive_prompt_ScribblePrompter_D3_2.yaml";
bsub  -R "tensorcore" -gpu num=1:j_exclusive=yes:mode=shared:gmem=10G -q gpu-debian -o /dkfz/cluster/gpu/data/OE0441/c306h/logs/%J.log -e /dkfz/cluster/gpu/data/OE0441/c306h/logs/%J.err ". ~/radioactive.sh  && python /home/c306h/radioactive/universal-models/src/radioa/experiments_runner.py --config ./configs/interactive_prompt_ScribblePrompter_D4_1.yaml";
bsub  -R "tensorcore" -gpu num=1:j_exclusive=yes:mode=shared:gmem=10G -q gpu-debian -o /dkfz/cluster/gpu/data/OE0441/c306h/logs/%J.log -e /dkfz/cluster/gpu/data/OE0441/c306h/logs/%J.err ". ~/radioactive.sh  && python /home/c306h/radioactive/universal-models/src/radioa/experiments_runner.py --config ./configs/interactive_prompt_ScribblePrompter_D4_2.yaml";
#bsub  -R "tensorcore" -gpu num=1:j_exclusive=yes:mode=shared:gmem=33G -q gpu-debian -o /dkfz/cluster/gpu/data/OE0441/c306h/logs/%J.log -e /dkfz/cluster/gpu/data/OE0441/c306h/logs/%J.err ". ~/radioactive.sh  && python /home/c306h/radioactive/universal-models/src/radioa/experiments_runner.py --config ./configs/interactive_prompt_ScribblePrompter_D5_1.yaml";
#bsub  -R "tensorcore" -gpu num=1:j_exclusive=yes:mode=shared:gmem=33G -q gpu-debian -o /dkfz/cluster/gpu/data/OE0441/c306h/logs/%J.log -e /dkfz/cluster/gpu/data/OE0441/c306h/logs/%J.err ". ~/radioactive.sh  && python /home/c306h/radioactive/universal-models/src/radioa/experiments_runner.py --config ./configs/interactive_prompt_ScribblePrompter_D5_2.yaml";
#bsub  -R "tensorcore" -gpu num=1:j_exclusive=yes:mode=shared:gmem=33G -q gpu-debian -o /dkfz/cluster/gpu/data/OE0441/c306h/logs/%J.log -e /dkfz/cluster/gpu/data/OE0441/c306h/logs/%J.err ". ~/radioactive.sh  && python /home/c306h/radioactive/universal-models/src/radioa/experiments_runner.py --config ./configs/interactive_prompt_ScribblePrompter_D6_1.yaml";
#bsub  -R "tensorcore" -gpu num=1:j_exclusive=yes:mode=shared:gmem=33G -q gpu-debian -o /dkfz/cluster/gpu/data/OE0441/c306h/logs/%J.log -e /dkfz/cluster/gpu/data/OE0441/c306h/logs/%J.err ". ~/radioactive.sh  && python /home/c306h/radioactive/universal-models/src/radioa/experiments_runner.py --config ./configs/interactive_prompt_ScribblePrompter_D6_2.yaml";
bsub  -R "tensorcore" -gpu num=1:j_exclusive=yes:mode=shared:gmem=10G -q gpu-debian -o /dkfz/cluster/gpu/data/OE0441/c306h/logs/%J.log -e /dkfz/cluster/gpu/data/OE0441/c306h/logs/%J.err ". ~/radioactive.sh  && python /home/c306h/radioactive/universal-models/src/radioa/experiments_runner.py --config ./configs/interactive_prompt_ScribblePrompter_D7_1.yaml";
bsub  -R "tensorcore" -gpu num=1:j_exclusive=yes:mode=shared:gmem=10G -q gpu-debian -o /dkfz/cluster/gpu/data/OE0441/c306h/logs/%J.log -e /dkfz/cluster/gpu/data/OE0441/c306h/logs/%J.err ". ~/radioactive.sh  && python /home/c306h/radioactive/universal-models/src/radioa/experiments_runner.py --config ./configs/interactive_prompt_ScribblePrompter_D7_2.yaml";
bsub  -R "tensorcore" -gpu num=1:j_exclusive=yes:mode=shared:gmem=10G -q gpu-debian -o /dkfz/cluster/gpu/data/OE0441/c306h/logs/%J.log -e /dkfz/cluster/gpu/data/OE0441/c306h/logs/%J.err ". ~/radioactive.sh  && python /home/c306h/radioactive/universal-models/src/radioa/experiments_runner.py --config ./configs/interactive_prompt_ScribblePrompter_D8_1.yaml";
bsub  -R "tensorcore" -gpu num=1:j_exclusive=yes:mode=shared:gmem=10G -q gpu-debian -o /dkfz/cluster/gpu/data/OE0441/c306h/logs/%J.log -e /dkfz/cluster/gpu/data/OE0441/c306h/logs/%J.err ". ~/radioactive.sh  && python /home/c306h/radioactive/universal-models/src/radioa/experiments_runner.py --config ./configs/interactive_prompt_ScribblePrompter_D8_2.yaml";
bsub  -R "tensorcore" -gpu num=1:j_exclusive=yes:mode=shared:gmem=10G -q gpu-debian -o /dkfz/cluster/gpu/data/OE0441/c306h/logs/%J.log -e /dkfz/cluster/gpu/data/OE0441/c306h/logs/%J.err ". ~/radioactive.sh  && python /home/c306h/radioactive/universal-models/src/radioa/experiments_runner.py --config ./configs/interactive_prompt_ScribblePrompter_D9_1.yaml";
bsub  -R "tensorcore" -gpu num=1:j_exclusive=yes:mode=shared:gmem=10G -q gpu-debian -o /dkfz/cluster/gpu/data/OE0441/c306h/logs/%J.log -e /dkfz/cluster/gpu/data/OE0441/c306h/logs/%J.err ". ~/radioactive.sh  && python /home/c306h/radioactive/universal-models/src/radioa/experiments_runner.py --config ./configs/interactive_prompt_ScribblePrompter_D9_2.yaml";
bsub  -R "tensorcore" -gpu num=1:j_exclusive=yes:mode=shared:gmem=10G -q gpu-debian -o /dkfz/cluster/gpu/data/OE0441/c306h/logs/%J.log -e /dkfz/cluster/gpu/data/OE0441/c306h/logs/%J.err ". ~/radioactive.sh  && python /home/c306h/radioactive/universal-models/src/radioa/experiments_runner.py --config ./configs/interactive_prompt_ScribblePrompter_D10_1.yaml";
bsub  -R "tensorcore" -gpu num=1:j_exclusive=yes:mode=shared:gmem=10G -q gpu-debian -o /dkfz/cluster/gpu/data/OE0441/c306h/logs/%J.log -e /dkfz/cluster/gpu/data/OE0441/c306h/logs/%J.err ". ~/radioactive.sh  && python /home/c306h/radioactive/universal-models/src/radioa/experiments_runner.py --config ./configs/interactive_prompt_ScribblePrompter_D10_2.yaml";
bsub  -R "tensorcore" -gpu num=1:j_exclusive=yes:mode=shared:gmem=10G -q gpu-debian -o /dkfz/cluster/gpu/data/OE0441/c306h/logs/%J.log -e /dkfz/cluster/gpu/data/OE0441/c306h/logs/%J.err ". ~/radioactive.sh  && python /home/c306h/radioactive/universal-models/src/radioa/experiments_runner.py --config ./configs/interactive_prompt_ScribblePrompter_D11_1.yaml";
bsub  -R "tensorcore" -gpu num=1:j_exclusive=yes:mode=shared:gmem=10G -q gpu-debian -o /dkfz/cluster/gpu/data/OE0441/c306h/logs/%J.log -e /dkfz/cluster/gpu/data/OE0441/c306h/logs/%J.err ". ~/radioactive.sh  && python /home/c306h/radioactive/universal-models/src/radioa/experiments_runner.py --config ./configs/interactive_prompt_ScribblePrompter_D11_2.yaml";

#static
bsub  -R "tensorcore" -gpu num=1:j_exclusive=yes:mode=shared:gmem=10G -q gpu-debian -o /dkfz/cluster/gpu/data/OE0441/c306h/logs/%J.log -e /dkfz/cluster/gpu/data/OE0441/c306h/logs/%J.err ". ~/radioactive.sh  && python /home/c306h/radioactive/universal-models/src/radioa/experiments_runner.py --config ./configs/static_prompt_ScribblePrompter_D1.yaml";
bsub  -R "tensorcore" -gpu num=1:j_exclusive=yes:mode=shared:gmem=10G -q gpu-debian -o /dkfz/cluster/gpu/data/OE0441/c306h/logs/%J.log -e /dkfz/cluster/gpu/data/OE0441/c306h/logs/%J.err ". ~/radioactive.sh  && python /home/c306h/radioactive/universal-models/src/radioa/experiments_runner.py --config ./configs/static_prompt_ScribblePrompter_D2.yaml";
bsub  -R "tensorcore" -gpu num=1:j_exclusive=yes:mode=shared:gmem=10G -q gpu-debian -o /dkfz/cluster/gpu/data/OE0441/c306h/logs/%J.log -e /dkfz/cluster/gpu/data/OE0441/c306h/logs/%J.err ". ~/radioactive.sh  && python /home/c306h/radioactive/universal-models/src/radioa/experiments_runner.py --config ./configs/static_prompt_ScribblePrompter_D3.yaml";
bsub  -R "tensorcore" -gpu num=1:j_exclusive=yes:mode=shared:gmem=10G -q gpu-debian -o /dkfz/cluster/gpu/data/OE0441/c306h/logs/%J.log -e /dkfz/cluster/gpu/data/OE0441/c306h/logs/%J.err ". ~/radioactive.sh  && python /home/c306h/radioactive/universal-models/src/radioa/experiments_runner.py --config ./configs/static_prompt_ScribblePrompter_D4.yaml";
bsub  -R "tensorcore" -gpu num=1:j_exclusive=yes:mode=shared:gmem=23G -q gpu-debian -o /dkfz/cluster/gpu/data/OE0441/c306h/logs/%J.log -e /dkfz/cluster/gpu/data/OE0441/c306h/logs/%J.err ". ~/radioactive.sh  && python /home/c306h/radioactive/universal-models/src/radioa/experiments_runner.py --config ./configs/static_prompt_ScribblePrompter_D5.yaml";
bsub  -R "tensorcore" -gpu num=1:j_exclusive=yes:mode=shared:gmem=10G -q gpu-debian -o /dkfz/cluster/gpu/data/OE0441/c306h/logs/%J.log -e /dkfz/cluster/gpu/data/OE0441/c306h/logs/%J.err ". ~/radioactive.sh  && python /home/c306h/radioactive/universal-models/src/radioa/experiments_runner.py --config ./configs/static_prompt_ScribblePrompter_D6.yaml";
bsub  -R "tensorcore" -gpu num=1:j_exclusive=yes:mode=shared:gmem=10G -q gpu-debian -o /dkfz/cluster/gpu/data/OE0441/c306h/logs/%J.log -e /dkfz/cluster/gpu/data/OE0441/c306h/logs/%J.err ". ~/radioactive.sh  && python /home/c306h/radioactive/universal-models/src/radioa/experiments_runner.py --config ./configs/static_prompt_ScribblePrompter_D7.yaml";
bsub  -R "tensorcore" -gpu num=1:j_exclusive=yes:mode=shared:gmem=10G -q gpu-debian -o /dkfz/cluster/gpu/data/OE0441/c306h/logs/%J.log -e /dkfz/cluster/gpu/data/OE0441/c306h/logs/%J.err ". ~/radioactive.sh  && python /home/c306h/radioactive/universal-models/src/radioa/experiments_runner.py --config ./configs/static_prompt_ScribblePrompter_D8.yaml";
bsub  -R "tensorcore" -gpu num=1:j_exclusive=yes:mode=shared:gmem=10G -q gpu-debian -o /dkfz/cluster/gpu/data/OE0441/c306h/logs/%J.log -e /dkfz/cluster/gpu/data/OE0441/c306h/logs/%J.err ". ~/radioactive.sh  && python /home/c306h/radioactive/universal-models/src/radioa/experiments_runner.py --config ./configs/static_prompt_ScribblePrompter_D9.yaml";
bsub  -R "tensorcore" -gpu num=1:j_exclusive=yes:mode=shared:gmem=10G -q gpu-debian -o /dkfz/cluster/gpu/data/OE0441/c306h/logs/%J.log -e /dkfz/cluster/gpu/data/OE0441/c306h/logs/%J.err ". ~/radioactive.sh  && python /home/c306h/radioactive/universal-models/src/radioa/experiments_runner.py --config ./configs/static_prompt_ScribblePrompter_D10.yaml";
#bsub  -R "tensorcore" -gpu num=1:j_exclusive=yes:mode=shared:gmem=33G -q gpu-debian -o /dkfz/cluster/gpu/data/OE0441/c306h/logs/%J.log -e /dkfz/cluster/gpu/data/OE0441/c306h/logs/%J.err ". ~/radioactive.sh  && python /home/c306h/radioactive/universal-models/src/radioa/experiments_runner.py --config ./configs/static_prompt_ScribblePrompter_D11.yaml";

