# Holds all information needed to run experiments.
seeds:
  - 11121
models:
  - "sam"
  # - "sammed2d"
  # - "medsam"
  # - "sammed3d"
  # - "sammed3d_turbo"
  # - "segvol"

prompting:
  type: "interactive"
  prompt_styles:
    - NPointsPer2DSliceInteractivePrompterNoPrevPoint
    - NPointsPer2DSliceInteractivePrompterWithPrevPrompt
    - threeDInteractivePrompterSAMMed3D
    - twoD1PointUnrealisticInteractivePrompterNoPrevPoint
    - twoD1PointUnrealisticInteractivePrompterWithPrevPoint

# List of dataset that will be compared in the next run of the benchmark.
datasets:
  - identifier: 201  # FLAIR MS instances
    type: "instance"
    excluded_classes: [0]
  - identifier: 501  # HNTS-MRG MR Primary Tumors
    type: "instance"
    excluded_classes: [0]
  - identifier: 911  # LNQ Metastatic Lymph Nodes
    type: "instance"
    excluded_classes: [0]
  - identifier: 912  # CT Colorectal Liver Metastases
    type: "instance"
    excluded_classes: [0]
  - identifier: 913  # Adrenal ACC Kidney
    type: "instance"
    excluded_classes: [0]
  - identifier: 921  # HCC TACE Liver instances
    type: "instance"
    excluded_classes: [0]
  - identifier: 930  # RIDER Lung CT
    type: "instance"
    excluded_classes: [0]
