# Holds all information needed to run experiments.
seeds:
  - 11121
models:
  # - "sam"
  - "sammed2d"
  # - "medsam"
  # - "sammed3d"
  # - "sammed3d_turbo"
  # - "segvol"

debug: True

prompting:
  type: "interactive"
  prompt_styles:
    - NPointsPer2DSliceInteractivePrompter
    - threeDInteractivePrompterSAMMed3D
    - twoDNPointsUnrealisticInteractivePrompter

# List of dataset that will be compared in the next run of the benchmark.
datasets:
  - identifier: 201  # FLAIR MS Lesions
    type: "lesion"
    excluded_classes: [0]
  - identifier: 501  # HNTS-MRG MR Primary Tumors
    type: "lesion"
    excluded_classes: [0]
  - identifier: 911  # LNQ Metastatic Lymph Nodes
    type: "lesion"
    excluded_classes: [0]
  - identifier: 912  # CT Colorectal Liver Metastases
    type: "lesion"
    excluded_classes: [0]
  - identifier: 913  # Adrenal ACC Kidney
    type: "lesion"
    excluded_classes: [0]
  - identifier: 921  # HCC TACE Liver Lesions
    type: "lesion"
    excluded_classes: [0]
  - identifier: 930  # RIDER Lung CT
    type: "lesion"
    excluded_classes: [0]
