# Holds all information needed to run experiments.
seeds:
  - 11121
models:
  # - "sam"
  # - "sammed2d"
  # - "medsam"
  - "sammed3d"
  # - "sammed3d_turbo"
  # - "segvol"

prompting:
  type: "interactive"
  prompt_styles:
    - NPointsPer2DSliceInteractivePrompterNoPrevPoint
    - NPointsPer2DSliceInteractivePrompterWithPrevPrompt
    - PointInterpolationInteractivePrompterNoPrevPoint
    - PointInterpolationInteractivePrompterWithPrevPoint
    - threeDInteractivePrompterSAMMed3D
    - twoD1PointUnrealisticInteractivePrompterNoPrevPoint
    - twoD1PointUnrealisticInteractivePrompterWithPrevPoint
  # ToDo: Add the hyperparameters for the prompters in here to have them properly defined and not depend on the defaults.

# List of dataset that will be compared in the next run of the benchmark.
datasets:
  - identifier: 209  # HanSeg MR Organs
    type: "organ"
    excluded_classes: [0]
  - identifier: 651  # SegRap CT Organs at Risk
    type: "organ"
    excluded_classes: [0]
  - identifier: 920  # HCC Tace CT Liver segmentation
    type: "organ"  # Choose from 'organ' or 'instance'; When instance we average over all instances, otherwise across organs.
    excluded_classes: [0] # List of classes to exclude from the dataset -- 0 is generally background
