# Holds all information needed to run experiments.
seeds:
  - 11121
models:
  - "sammed3d"
  - "sam"
  - "sammed2d"
  - "medsam"
  # - "sammed3d_turbo"
  # - "segvol"

debug: False

prompting:
  type: "static"
  prompt_styles:
    - "NPointsPer2DSlicePrompter"
    - "PointInterpolationPrompter"
    - "PointPropagationPrompter"
    - "BoxPer2DSlicePrompter"
    - "BoxPer2dSliceFrom3DBoxPrompter"
    - "BoxInterpolationPrompter"
    - "BoxPropagationPrompter"
    - "NPoints3DVolumePrompter"
    - "Box3DVolumePrompter"
  # ToDo: Add the hyperparameters for the prompters in here to have them properly defined and not depend on the defaults.

# List of dataset that will be compared in the next run of the benchmark.
datasets:
  - identifier: 070
    type: "lesion"  # Choose from 'organ' or 'lesion'; When lesion we average over all lesions, otherwise across organs.
    excluded_classes: [0] # List of classes to exclude from the dataset -- 0 is generally background
