# Holds all information needed to run experiments.
seeds:
  - 11121
models:
#  - "sam2"
  # - "sammed2d"
  # - "medsam"
  # - "sammed3d"
  # - "sammed3d_turbo"
  # - "segvol"
  - "scribbleprompter"

only_calc: false
only_eval: false

prompting:
  type: "static"
  prompt_styles:
    # ----------------------------------- 2D Point ---------------------------------- #
    - "OneFGPointsPer2DSlicePrompter"
    - "TwoFGPointsPer2DSlicePrompter"
    - "ThreeFGPointsPer2DSlicePrompter"
    - "FiveFGPointsPer2DSlicePrompter"
    - "TenFGPointsPer2DSlicePrompter"
    - "CenterPointPrompter"
    - "Alternating2PointsPer2DSlicePrompter"
    - "Alternating3PointsPer2DSlicePrompter"
    - "Alternating5PointsPer2DSlicePrompter"
    - "Alternating10PointsPer2DSlicePrompter"
    - "ThreePointInterpolationPrompter"
    - "FivePointInterpolationPrompter"
    - "TenPointInterpolationPrompter"
    - "PointPropagationPrompter"
    # ------------------------------------ 2D Box ----------------------------------- #
    - "BoxPer2DSlicePrompter"
    - "BoxPer2dSliceFrom3DBoxPrompter"
    - "ThreeBoxInterpolationPrompter"
    - "FiveBoxInterpolationPrompter"
    - "TenBoxInterpolationPrompter"
    - "BoxPropagationPrompter"
    # ----------------------------------- 3D Point ---------------------------------- #
    - "OnePoints3DVolumePrompter"
    - "TwoPoints3DVolumePrompter"
    - "ThreePoints3DVolumePrompter"
    - "FivePoints3DVolumePrompter"
    - "TenPoints3DVolumePrompter"
    - "OnePointsFromCenterCropped3DVolumePrompter"
    - "TwoPointsFromCenterCropped3DVolumePrompter"
    - "ThreePointsFromCenterCropped3DVolumePrompter"
    - "FivePointsFromCenterCropped3DVolumePrompter"
    - "TenPointsFromCenterCropped3DVolumePrompter"
    # ------------------------------------ 3D Box ----------------------------------- #
    - "Box3DVolumePrompter"

# List of dataset that will be compared in the next run of the benchmark.
datasets:

#  - identifier: 201  # FLAIR MS instances
#    type: "instance"
#    excluded_classes: [0]
  # - identifier: 209  # HanSeg MR Organs
  #   type: "organ"
  #   excluded_classes: [0]
  # - identifier: 501  # HNTS-MRG MR Primary Tumors
  #   type: "instance"
  #   excluded_classes: [0]
  # # - identifier: 600  # Pengwin CT Bones
  # #   type: "instance"
  # #   excluded_classes: [0]
  # - identifier: 911  # LNQ Metastatic Lymph Nodes
  #   type: "instance"
  #   excluded_classes: [0]
  # - identifier: 912  # CT Colorectal Liver Metastases
  #   type: "instance"
  #   excluded_classes: [0]
   - identifier: 913  # Adrenal ACC Kidney
     type: "instance"
     excluded_classes: [0]
  # - identifier: 920  # HCC Tace CT Liver segmentation
  #   type: "organ"  # Choose from 'organ' or 'instance'; When instance we average over all instances, otherwise across organs.
  #   excluded_classes: [0] # List of classes to exclude from the dataset -- 0 is generally background
  # - identifier: 921  # HCC TACE Liver instances
  #   type: "instance"
  #   excluded_classes: [0]
  # - identifier: 930  # RIDER Lung CT
  #   type: "instance"

  #   excluded_classes: [0]
  # - identifier: 651  # SegRap CT Organs at Risk
  #   type: "organ"
  #   excluded_classes: [0]
