# Holds all information needed to run experiments.
seeds:
  - 11121
models:
  - "sam"
  - "sammed2d"
  - "medsam"
  - "sammed3d"
  # - "sammed3d_turbo"
  # - "segvol"

debug: True

prompting:
  type: "interactive"
  prompt_styles:
    - "NPointsPer2DSliceInteractivePrompter"
    - "threeDInteractivePrompterSAMMed3D"
    - twoD1PointUnrealisticInteractivePrompterNoPrevPointPassed
    - twoD1PointUnrealisticInteractivePrompterPrevPointPassed

# List of dataset that will be compared in the next run of the benchmark.
datasets:
  - identifier: 70
    type: "lesion"  # Choose from 'organ' or 'lesion'; When lesion we average over all lesions, otherwise across organs.
    excluded_classes: [0] # List of classes to exclude from the dataset -- 0 is generally background
