# Holds all information needed to run experiments.
seeds:
  - 11121
models:
  # - "sam"
  - "sammed2d"
  - "medsam"
  - "sammed3d"
  - "sammed3d_turbo"
  # - "segvol"

prompting:
  type: "static"
  prompt_styles:
  # ----------------------------------- 2D Point ---------------------------------- #
    # - "OneFGPointsPer2DSlicePrompter"
    # - "TwoFGPointsPer2DSlicePrompter"
    # - "ThreeFGPointsPer2DSlicePrompter"
    # - "FiveFGPointsPer2DSlicePrompter"
    # - "TenFGPointsPer2DSlicePrompter"
    - "CenterPointPrompter"
    # - "Alternating2PointsPer2DSlicePrompter"
    # - "Alternating3PointsPer2DSlicePrompter"
    # - "Alternating5PointsPer2DSlicePrompter"
    # - "Alternating10PointsPer2DSlicePrompter"
    # - "PointInterpolationPrompter"
    # - "PointPropagationPrompter"
    # ------------------------------------ 2D Box ----------------------------------- #
    # - "BoxPer2DSlicePrompter"
    - "BoxPer2dSliceFrom3DBoxPrompter"
    # - "BoxInterpolationPrompter"
    # - "BoxPropagationPrompter"
    # ----------------------------------- 3D Point ---------------------------------- #
    - "OnePoints3DVolumePrompter"
    # - "TwoPoints3DVolumePrompter"
    # - "ThreePoints3DVolumePrompter"
    # - "FivePoints3DVolumePrompter"
    # - "TenPoints3DVolumePrompter"
    # ------------------------------------ 3D Box ----------------------------------- #
    - "Box3DVolumePrompter"

datasets:
  - identifier: 50
    type: "instance"  # Choose from 'organ' or 'instance'; When instance we average over all instances, otherwise across organs.
    excluded_classes: [0] # List of classes to exclude from the dataset -- 0 is generally background
  - identifier: 60
    type: "instance"  # Choose from 'organ' or 'instance'; When instance we average over all instances, otherwise across organs.
    excluded_classes: [0] # List of classes to exclude from the dataset -- 0 is generally background
  - identifier: 70
    type: "instance"  # Choose from 'organ' or 'instance'; When instance we average over all instances, otherwise across organs.
    excluded_classes: [0] # List of classes to exclude from the dataset -- 0 is generally background
  - identifier: 80
    type: "instance"  # Choose from 'organ' or 'instance'; When instance we average over all instances, otherwise across organs.
    excluded_classes: [0] # List of classes to exclude from the dataset -- 0 is generally background
  - identifier: 90
    type: "instance"  # Choose from 'organ' or 'instance'; When instance we average over all instances, otherwise across organs.
    excluded_classes: [0] # List of classes to exclude from the dataset -- 0 is generally background
  - identifier: 100
    type: "instance"  # Choose from 'organ' or 'instance'; When instance we average over all instances, otherwise across organs.
    excluded_classes: [0] # List of classes to exclude from the dataset -- 0 is generally background
  # - identifier: 110
  #   type: "instance"  # Choose from 'organ' or 'instance'; When instance we average over all instances, otherwise across organs.
  #   excluded_classes: [0] # List of classes to exclude from the dataset -- 0 is generally background