# Holds all information needed to run experiments.
seeds:
  - 11121
models:
  # - "sam"
  - "sammed2d"
  # - "medsam"
  # - "sammed3d"
  # - "sammed3d_turbo"
  # - "segvol"

debug: True

prompting:
  type: "static"
  prompt_styles:
  # ----------------------------------- 2D Point ---------------------------------- #
    - "OneFGPointsPer2DSlicePrompter"
    # - "TwoFGPointsPer2DSlicePrompter"
    # - "ThreeFGPointsPer2DSlicePrompter"
    # - "FiveFGPointsPer2DSlicePrompter"
    # - "TenFGPointsPer2DSlicePrompter"
    # - "CenterPointPrompter"
    # - "PointInterpolationPrompter"
    # - "PointPropagationPrompter"
    # - "BoxPer2DSlicePrompter"
    # - "BoxPer2dSliceFrom3DBoxPrompter"
    # - "BoxInterpolationPrompter"
    # - "BoxPropagationPrompter"
    # - "OnePoints3DVolumePrompter"
    # - "TwoPoints3DVolumePrompter"
    # - "ThreePoints3DVolumePrompter"
    # - "FivePoints3DVolumePrompter"
    # - "TenPoints3DVolumePrompter"
    # - "Box3DVolumePrompter"
  # ToDo: Add the hyperparameters for the prompters in here to have them properly defined and not depend on the defaults.

# List of dataset that will be compared in the next run of the benchmark.
datasets:
  - identifier: 350  # JHU Abdomen
    type: "organ"  # Choose from 'organ' or 'lesion'; When lesion we average over all lesions, otherwise across organs.
    excluded_classes: [0,1,2,4,5,6,7,8,9] # List of classes to exclude from the dataset -- 0 is generally background
